### PR TITLE
Upgrade gems

### PR DESCRIPTION
**Pull request by jonatasrancan**

### CODE REVIEW

**Comment by jonatasrancan** [comment]
@milespj should all the tests pass locally?
Because event doing the `export` that is explained on the README, for the user, password and host, some tests failed because I got ` Invalid username/password`

**Comment by milespj** [comment]
Hey @jonatasrancan - is this a new test failure? Looks like the tests have failed for some time. Assuming that this isn't a new test failure, the issue you report sounds like it could be fixed by setting up the proper user. Either @andreibondarev or @scottsmith130 can set up the account being used for testing.

**Comment by andreibondarev** [comment]
[pmp-support: Fix TravisCI issues](https://trello.com/c/7tPG6xig/1-pmp-support-fix-travisci-issues)

**Comment by jonatasrancan** [comment]
[pmp-support: Upgrade gems to get rid of Github's security vulnerability warnings](https://trello.com/c/Z8xvcKlz/3-pmp-support-upgrade-gems-to-get-rid-of-githubs-security-vulnerability-warnings)

**Comment by andreibondarev** [comment]
@milespj I think this is good to go

**Pull request merged**
